### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by frankruegamer** [OndrejSkalicka/aax-to-mp3-python#3]
I takes quite a long time to convert one audio book (18+ minutes) currently. Would it be possible to convert audio files using multiple cpu cores?
It seems that ffmpeg has a `-threads` option.

**Comment by OndrejSkalicka** [comment]
Haven't tested myself, if you create PR I can merge

**Comment by frankruegamer** [comment]
Unfortunately that option apparently depends on the used encoder, adding it didn't make any difference, on the contrary, my last conversion took over 1h.

**Comment by OndrejSkalicka** [comment]
Shame.. :/ well, no point adding it then. This operation will unfortunately take some time. Closing the issue as there is not much to do here.
