### ISSUE TITLE
Invalid syntax when running the python script

### ISSUE THREAD

**Issue by NorthyIE** [OndrejSkalicka/aax-to-mp3-python#4]
Hi, when I run your script on my Debian 9 Stretch, I get the following error:

```
user@laptop:~/aax-to-mp3-python# python convert.py -i "Book.aax" -a abcdefgh
  File "convert.py", line 49
    output = f'{out_arg}_{i+1}.mp3'
                                  ^
SyntaxError: invalid syntax
```
I made sure that ffmpeg, etc. are installed.
It also makes no difference if I use python 2 (2.7.13) or 3 (3.5.3),

Any idea what the problem could be?

**Comment by OndrejSkalicka** [comment]
Hi @NorthyIE , seems like the f' syntax is in python 3.6 up. I updated the readme.

If that is a problem, just replace the line with 

```python
output = '%s_%d.mp3' % (out_arg, i + 1)
```
should work on 3.5 then.

**Comment by NorthyIE** [comment]
Thanks for the feedback, this works fine for me 👍
